---
title: "LLC_timecourse_all_cells"
author: "Alex Brown"
date: "2025-07-15"
output: html_document
---



# Load packages

```{r setup, include=FALSE}
library(Seurat)
library(SeuratWrappers)
library(tidyverse)
library(Biobase)
library(BiocGenerics)
library(ggplot2)
library(cowplot)
library(grid)
library(gridExtra)
library(RColorBrewer)
library(ggbeeswarm)
library(pheatmap)
library(viridis)
library(monocle3)
library(EnhancedVolcano)
library(presto)
library(clusterProfiler)
library(AnnotationDbi)
library(org.Mm.eg.db)
# NOTE that the org.Mm.eg.db is for mice, org.Hs.eg.db is for humans
```



# Read in the data

```{r, include=FALSE}
load("C:/Users/nwb_l/Documents/r_projects/LLC_timecourse/LLC_timecourse_processed.RData")
```



# DE genes per condition all clusters

```{r, include=FALSE}
Idents(LLC_combined) <- "orig.ident"

DEGs_2vSham <- FindMarkers(LLC_combined, ident.1 = "2_weeks", ident.2 = "Sham", logfc.threshold = 0, min.pct = 0.10, verbose = FALSE)
DEGs_2.5vSham <- FindMarkers(LLC_combined, ident.1 = "2.5_weeks", ident.2 = "Sham", logfc.threshold = 0, min.pct = 0.10, verbose = FALSE)
DEGs_3.5vSham <- FindMarkers(LLC_combined, ident.1 = "3.5_weeks", ident.2 = "Sham", logfc.threshold = 0, min.pct = 0.10, verbose = FALSE)

DEGs_2vSham <- DEGs_2vSham %>% 
  mutate(log10_p_val_adj = -log10(p_val_adj))
DEGs_2.5vSham <- DEGs_2.5vSham %>% 
  mutate(log10_p_val_adj = -log10(p_val_adj))
DEGs_3.5vSham <- DEGs_3.5vSham %>% 
  mutate(log10_p_val_adj = -log10(p_val_adj))
```

```{r, include=FALSE}
write.csv(DEGs_2vSham, file = "DEGs_2vSham.csv", row.names = TRUE)
write.csv(DEGs_2.5vSham, file = "DEGs_2.5vSham.csv", row.names = TRUE)
write.csv(DEGs_3.5vSham, file = "DEGs_3.5vSham.csv", row.names = TRUE)
```



# Volcano plots for DE genes per condition all clusters

```{r}
keyvals <- ifelse(DEGs_2vSham$avg_log2FC > 0 & DEGs_2vSham$p_val_adj < 0.05, 
                  "blue", 
           ifelse(DEGs_2vSham$avg_log2FC < 0 & DEGs_2vSham$p_val_adj < 0.05, 
                  "red", 
                  "grey"))

names(keyvals) <- rownames(DEGs_2vSham)

EnhancedVolcano(DEGs_2vSham,
  lab = rownames(DEGs_2vSham),
  x = "avg_log2FC",
  y = "p_val_adj",
  title = "2 weeks vs. Sham",
  pCutoff = 0.05,
  FCcutoff = 0.2,
  colCustom = keyvals
) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    plot.subtitle = element_blank(),
    plot.caption = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  ) +
  xlim(-5, 5)



keyvals <- ifelse(DEGs_2.5vSham$avg_log2FC > 0 & DEGs_2.5vSham$p_val_adj < 0.05, 
                  "blue", 
           ifelse(DEGs_2.5vSham$avg_log2FC < 0 & DEGs_2.5vSham$p_val_adj < 0.05, 
                  "red", 
                  "grey"))

names(keyvals) <- rownames(DEGs_2.5vSham)

EnhancedVolcano(DEGs_2.5vSham,
  lab = rownames(DEGs_2.5vSham),
  x = "avg_log2FC",
  y = "p_val_adj",
  title = "2.5 weeks vs. Sham",
  pCutoff = 0.05,
  FCcutoff = 0.2,
  colAlpha = 1,
  colCustom = keyvals
) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    plot.subtitle = element_blank(),
    plot.caption = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  ) +
  xlim(-5, 5)


keyvals <- ifelse(DEGs_3.5vSham$avg_log2FC > 0 & DEGs_3.5vSham$p_val_adj < 0.05, 
                  "blue", 
           ifelse(DEGs_3.5vSham$avg_log2FC < 0 & DEGs_3.5vSham$p_val_adj < 0.05, 
                  "red", 
                  "grey"))

names(keyvals) <- rownames(DEGs_3.5vSham)

EnhancedVolcano(DEGs_3.5vSham,
  lab = rownames(DEGs_3.5vSham),
  x = "avg_log2FC",
  y = "p_val_adj",
  title = "3.5 weeks vs. Sham",
  pCutoff = 0.05,
  FCcutoff = 0.2,
  colAlpha = 1,
  colCustom = keyvals
) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    plot.subtitle = element_blank(),
    plot.caption = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  ) +
  xlim(-5, 5)
```



# GO analyses

## Subset DEG for p_val_adj < 0.05
```{r, include=FALSE}
DEGs_2vSham_sig <- na.omit(DEGs_2vSham)
DEGs_2vSham_sig <- subset(DEGs_2vSham, p_val_adj < 0.05)

DEGs_2.5vSham_sig <- na.omit(DEGs_2.5vSham)
DEGs_2.5vSham_sig <- subset(DEGs_2.5vSham, p_val_adj < 0.05)

DEGs_3.5vSham_sig <- na.omit(DEGs_3.5vSham)
DEGs_3.5vSham_sig <- subset(DEGs_3.5vSham, p_val_adj < 0.05)
```


## Take the row names of the specified genes in each condition that have an -2 > avg_log2FC > 0.2

```{r, include=FALSE}
DEGs_2vSham_sig_upgenes <- rownames(DEGs_2vSham_sig[DEGs_2vSham_sig$avg_log2FC > 0.2,])

DEGs_2.5vSham_sig_upgenes <- rownames(DEGs_2.5vSham_sig[DEGs_2.5vSham_sig$avg_log2FC > 0.2,])

DEGs_3.5vSham_sig_upgenes <- rownames(DEGs_3.5vSham_sig[DEGs_3.5vSham_sig$avg_log2FC > 0.2,])

DEGs_2vSham_sig_downgenes <- rownames(DEGs_2vSham_sig[DEGs_2vSham_sig$avg_log2FC < -0.2,])

DEGs_2.5vSham_sig_downgenes <- rownames(DEGs_2.5vSham_sig[DEGs_2.5vSham_sig$avg_log2FC < -0.2,])

DEGs_3.5vSham_sig_downgenes <- rownames(DEGs_3.5vSham_sig[DEGs_3.5vSham_sig$avg_log2FC < -0.2,])
```


## Run GO analysis

```{r, include=FALSE}
DEGs_2vSham_upgo <- enrichGO(gene = DEGs_2vSham_sig_upgenes, OrgDb = "org.Mm.eg.db", keyType = "SYMBOL", ont = "BP")
DEGs_2vSham_downgo <- enrichGO(gene = DEGs_2vSham_sig_downgenes, OrgDb = "org.Mm.eg.db", keyType = "SYMBOL", ont = "BP")

DEGs_2.5vSham_upgo <- enrichGO(gene = DEGs_2.5vSham_sig_upgenes, OrgDb = "org.Mm.eg.db", keyType = "SYMBOL", ont = "BP")
DEGs_2.5vSham_downgo <- enrichGO(gene = DEGs_2.5vSham_sig_downgenes, OrgDb = "org.Mm.eg.db", keyType = "SYMBOL", ont = "BP")

DEGs_3.5vSham_upgo <- enrichGO(gene = DEGs_3.5vSham_sig_upgenes, OrgDb = "org.Mm.eg.db", keyType = "SYMBOL", ont = "BP")
DEGs_3.5vSham_downgo <- enrichGO(gene = DEGs_3.5vSham_sig_downgenes, OrgDb = "org.Mm.eg.db", keyType = "SYMBOL", ont = "BP")
```


## .csv for GO terms

```{r, include=FALSE}
write.csv(DEGs_2vSham_upgo, file = "DEGs_2vSham_upgo.csv", row.names = TRUE)
write.csv(DEGs_2vSham_downgo, file = "DEGs_2vSham_downgo.csv", row.names = TRUE)
write.csv(DEGs_2.5vSham_upgo, file = "DEGs_2.5vSham_upgo.csv", row.names = TRUE)
write.csv(DEGs_2.5vSham_downgo, file = "DEGs_2.5vSham_downgo.csv", row.names = TRUE)
write.csv(DEGs_3.5vSham_upgo, file = "DEGs_3.5vSham_upgo.csv", row.names = TRUE)
write.csv(DEGs_3.5vSham_downgo, file = "DEGs_3.5vSham_downgo.csv", row.names = TRUE)

```


## Plot the top 10 GO terms

```{r}
ggplot(data = DEGs_2vSham_upgo[1:10, ], 
       aes(x = Count, y = reorder(Description, Count), fill = p.adjust)) +
  geom_col() +
  labs(title = "UP 2 weeks", y = "") +
  theme(panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA),
        axis.line = element_line(color = "black")) +
  scale_fill_gradient(low = "#4575B4", high = "#91BFDB")

ggplot(data = DEGs_2vSham_downgo[1:10, ], 
       aes(x = Count, y = reorder(Description, Count), fill = p.adjust)) +
  geom_col() +
  labs(title = "DOWN 2 weeks", y = "") +
  theme(panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA),
        axis.line = element_line(color = "black")) +
  scale_fill_gradient(low = "#D73027", high = "#FEE090")



ggplot(data = DEGs_2.5vSham_upgo[1:10, ], 
       aes(x = Count, y = reorder(Description, Count), fill = p.adjust)) +
  geom_col() +
  labs(title = "UP 2.5 weeks", y = "") +
  theme(panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA),
        axis.line = element_line(color = "black")) +
  scale_fill_gradient(low = "#4575B4", high = "#91BFDB")

ggplot(data = DEGs_2.5vSham_downgo[1:10, ], 
       aes(x = Count, y = reorder(Description, Count), fill = p.adjust)) +
  geom_col() +
  labs(title = "DOWN 2.5 weeks", y = "") +
  theme(panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA),
        axis.line = element_line(color = "black")) +
  scale_fill_gradient(low = "#D73027", high = "#FEE090")



ggplot(data = DEGs_3.5vSham_upgo[1:10, ], 
       aes(x = Count, y = reorder(Description, Count), fill = p.adjust)) +
  geom_col() +
  labs(title = "UP 3.5 weeks", y = "") +
  theme(panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA),
        axis.line = element_line(color = "black")) +
  scale_fill_gradient(low = "#4575B4", high = "#91BFDB")

ggplot(data = DEGs_3.5vSham_downgo[1:10, ], 
       aes(x = Count, y = reorder(Description, Count), fill = p.adjust)) +
  geom_col() +
  labs(title = "DOWN 3.5 weeks", y = "") +
  theme(panel.background = element_blank(),
        plot.background = element_rect(fill = "transparent", color = NA),
        axis.line = element_line(color = "black")) +
  scale_fill_gradient(low = "#D73027", high = "#FEE090")
```
